root: true
overrides:
  - files: ["*.ts"]
    extends:
      - "eslint:recommended"
      - "plugin:@typescript-eslint/recommended"
      - "plugin:@angular-eslint/recommended"
      - "plugin:@angular-eslint/template/process-inline-templates"
    rules:
      "semi": [2, never]
      "curly": [2, multi]
  - files: ["*.html"]
    extends:
      - "plugin:@angular-eslint/template/recommended"
      - "plugin:@angular-eslint/template/accessibility"
